#!/bin/bash
################################################################################
# @author      Anderson Deluiz <anderson.santos@gpnet.com.br>                  #
# @name        docker-aliases                                                  #
# @version     1.0                                                             #
# @date        Jan 5th, 2014                                                   #
# @description Aliases para simplificar o uso de comandos docker.              #
#                                                                              #
# @require     N/A                                                             #
#                                                                              #
# @usage       Para carregar os aliases, estando no bash prompt execute:       #
#              # . docker-aliases                                              #
#                                                                              #
################################################################################

#---------------------------        INCLUDE       -----------------------------#

#---------------------------     DEBUG OPTIONS    -----------------------------#
# uncomment line(s) to activate debug function
# set -x    # print a trace of simple commands and their arguments
# set -v    # print shell input lines as they are read
# set -n    # read commands but do not execute them

#---------------------------   GLOBAL VARIABLES   -----------------------------#
myName=$(basename $0)
OSName=$(uname -s)
myVersion=$(awk '/^# @version/ {print $3}' ${myName})
myHostname=$(hostname)

# Cria array associativo com diretorios padrao de localizacao de Dockerfile
declare -A buildDirectoryDefault
buildDirectoryDefault[app]=/opt/docker/build/siga-appserver-standalone
buildDirectoryDefault[web]=/opt/docker/build/siga-webserver-standalone

# Text output modifiers
textBold=$(tput bold)
textReverse=$(tput rev)
textNormal=$(tput sgr0)

#---------------------------       FUNCTIONS      -----------------------------#

#------------------------------------------------------------------------------#
# @function    usage                                                           #
# @description Displays usage of this script and help messages and exit script.#
#                                                                              #
# @usage       usage                                                           #
# @in          none                                                            #
# @return      none                                                            #
# @return-code                                                                 #
#              none                                                            #
# @exit-code                                                                   #
#              255 - normal exit code                                          #
#------------------------------------------------------------------------------#
usage()
{
   cat << _EOF_
${textBold}
${myName} v${myVersion}

Uso: ${myName} COMANDO [ARGS] 

Provê funções básicas de uso para imagens Docker utilizadas pela aplicação SIGA.

Comandos:
${textNormal}
${textBold}   build <buildType> [buildDirectory]${textNormal}
        Cria uma imagem a partir de um Dockerfile.
        Argumentos:
           buildType - especifica que tipo de imagem sera criada.
              Tipo de imagem:
                 app - Servidor de aplicação JBoss standalone
                 web - Servidor Apache HTTPD
           buildDirectory - diretório onde está localizado o arquivo Dockerfile.

${textBold}   rmi <ImageType> [BuildNumber]${textNormal}
        Remove imagem do tipo indicado por ImageType. Caso não seja informado o
        BuildNumber, serão mostradas todas as imagens disponíveis para escolha.
        Argumentos:
           ImageType - especifica que tipo de imagem sera executada.
              Tipo de imagem:
                 app - Servidor de aplicação JBoss standalone
                 web - Servidor Apache HTTPD

${textBold}   help${textNormal}
        Exibe esta mensagem de utilização do aplicativo.

${textBold}   run <ImageType> [BuildNumber]${textNormal}
        Executa imagem do tipo indicado por ImageType. Caso não seja informado o
        BuildNumber, será executada a imagem mais recente.
        Argumentos:
           ImageType - especifica que tipo de imagem sera executada.
              Tipo de imagem:
                 app - Servidor de aplicação JBoss standalone
                 web - Servidor Apache HTTPD

${textBold}   version${textNormal}
        Exibe somente a versão deste aplicativo.

_EOF_

   exit 255
}

#------------------------------------------------------------------------------#
# @function    sigaBuild                                                       #
# @description Builds Docker images and tags them.                             #
#                                                                              #
# @usage       sigaBuild <buildType> [buildDirectory]                          #
# @in          none                                                            #
# @return      none                                                            #
# @return-code                                                                 #
#              none                                                            #
# @exit-code                                                                   #
#              0 - success                                                     #
#------------------------------------------------------------------------------#
sigaBuild ()
{
   local -a arrayImages
   local lastBuildNumber buildType buildDirectory

   buildType=$1
   buildDirectory=${buildDirectoryDefault[${buildType}]}

   if [ $# -eq 2 ]
   then
      buildDirectory=$2
   fi

   if [ ! -r ${buildDirectory}/Dockerfile ]
   then
      echo "${textBold}ERROR: File ${buildDirectory}/Dockerfile doesn't exist or doesn't have read permission.${textNormal}"
      return 1
   fi

   # Carrega array com imagens ordenadas do decrescentemente pelo build number.
   # Desta forma, o build mais recente sempre sera o que vira primeiro no array.
   arrayImages=($(docker images siga/${buildType}server | awk '{if (NR != 1) if ($2 ~ /build-[0-9]*/) print $1":"$2}' | sort -r))

   lastBuildNumber=$(cut -d'-' -f 2 <<< ${ArrayImages[0]})
   newBuildNumber=$(printf "%05d" $((lastBuildNumber + 1)))

   echo "Last Build number is: ${textBold}${lastBuildNumber}${textNormal}"
   echo "New Build number will be: ${textBold}${newBuildNumber}${textNormal}"

   echo "Building New Image! Please wait..."
   docker build --tag=siga/${buildType}server:build-${newBuildNumber} --no-cache --force-rm ${buildDirectory} 

   if [ $? -eq 0 ]
   then
      echo
      echo "${textBold}Successfully built image siga/${buildType}server:build-${newBuildNumber}${textNormal}!!!"
      echo 
      docker tag siga/${buildType}server:build-${newBuildNumber} siga/${buildType}server:latest
      if [ $? -eq 0 ]
      then
         echo "${textBold}Image siga/${buildType}server:build-${newBuildNumber} tagged as siga/${buildType}server:latest${textNormal}"
         return 0
      fi
      echo "WARNING: Couldn't tag image ${textBold}siga/${buildType}server:build-${newBuildNumber}${textNormal} as ${textBold}siga/${buildType}server:latest${textNormal}"
      return 0
   fi

   return 2
}

#------------------------------------------------------------------------------#
# @function    sigaRun                                                         #
# @description Runs Docker images in detach (background) mode.                 #
#                                                                              #
# @usage       sigaRun <imageType> [buildNumber] [newEntrypoint]               #
# @in          imageType - type of image to run                                #
#              buildNumber - build number of image. Defaults to "latest"       #
#              newEntrypoint - undocumented argument. Changes entrypoint of    #
#                 image and run in interactive mode.                           #
# @return      none                                                            #
# @return-code Returns return-code from docker execution.                      #
# @exit-code   none                                                            #
#------------------------------------------------------------------------------#
sigaRun()
{
   declare -a arrayImages
   declare -A defaultPorts
   local imageType buildNumber newEntrypoint tempPort exposeTCPPorts cmdToRun imageTag

   # Load array of default TCP Ports to map
   defaultPorts[app]=8080,8443,9990
   defaultPorts[web]=80,443

   [ $# -lt 1 -o $# -gt 3 ] && usage

   imageType=$1
   buildNumber=$2
   newEntrypoint=$3

   for tempPort in $(tr ',' ' ' <<< ${defaultPorts[${imageType}]})
   do
      exposeTCPPorts="${exposeTCPPorts} -p ${tempPort}:${tempPort}"
   done

   cmdToRun="docker run --name=\"siga-${imageType}server\" -h \"siga-${imageType}server\" ${exposeTCPPorts}"

   if [ ${newEntrypoint} ]
   then
      cmdToRun="${cmdToRun} --entrypoint=\"${newEntrypoint}\" -it"
   else
      cmdToRun="${cmdToRun} -d"
   fi

   [ ${buildNumber} ] && imageTag="build-${buildNumber}"

   case ${imageType} in
      'app')
         ${cmdToRun} siga/${imageType}server:${imageTag:-latest}
         return $?
         ;;

      'web')
         ${cmdToRun} --link=siga-appserver:siga-appserver siga/${imageType}server:${imageTag:-latest}
         return $?
         ;;
      *)
         usage
         ;;
   esac
}

#------------------------------------------------------------------------------#
# @function    sigaRemoveContainer                                             #
# @description Removes a Docker stopped container.                             #
#                                                                              #
# @usage       sigaRemoveContainer                                             #
# @in          none                                                            #
# @return      none                                                            #
# @return-code                                                                 #
#              none                                                            #
# @exit-code                                                                   #
#              none                                                            #
#------------------------------------------------------------------------------#
sigaRemoveContainer()
{
   declare -a arrayContainers

   arrayContainers=($(docker ps -a | sed -n '1!p' ))
}

#------------------------------------------------------------------------------#
# @function    sigaRemoveImage                                                 #
# @description Builds Docker images and tags them.                             #
#                                                                              #
# @usage       sigaRemoveImage <buildType> [buildDirectory]                    #
# @in          none                                                            #
# @return      none                                                            #
# @return-code                                                                 #
#              none                                                            #
# @exit-code                                                                   #
#              none                                                            #
#------------------------------------------------------------------------------#
sigaRemoveImage()
{
   :
}
#---------------------------     MAIN SECTION     -----------------------------#

if [ $# -eq 0 ]
then
   usage
fi

# Efetua parsing inicial dos comandos passados via prompt
case $1 in
   'build')
      shift
      sigaBuild $@
      exit $?
      ;;
   'rm')
      shift
      sigaRemoveContainer $@
      exit $?
      ;;
   'rmi')
      shift
      sigaRemoveImage $@
      exit $?
      ;;
   'run')
      shift
      sigaRun $@
      exit $?
      ;;
   'help')
      usage
      ;;
   'version')
      echo
      echo "${myName} v${myVersion}"
      echo
      exit 255
      ;;
   *)
      usage
      ;;
esac

exit 0


# Executa conteiners em segundo plano
#
#alias siga-rmi-webserver="docker rmi siga:webserver"
#alias siga-rmi-appserver="docker rmi siga/appserver:latest && docker rmi 10.34.15.71:5000/centos-jboss-02"


################################################################################
# Iniciar aplicacao Siga no conteiner
#
# mkdir -p /var/log/jboss/sigadoc \
#    && cd /opt/jboss/bin \
#    && ./standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 -Djboss.home.dir=/opt/jboss -Djboss.server.base.dir=/opt/jboss/sigadoc/ -Djboss.server.log.dir=/var/log/jboss -Djboss.socket.binding.port-offset=0

################################################################################
# Para "attachar" a um conteiner em execucao e sair sem para o conteiner:
#
# 1. "Attachar" ao conteiner com o comando :
#
#    # docker attach --sig-proxy=false NAME
#
# 2. Verificar o que for preciso no conteiner.
#
# 3. Sair do conteiner utilizando CTRL+C.

